version: 0.2

phases:
  install:
    commands:
      - echo test here lol
      - aws cloudformation create-stack --stack-name CloudFormationFromGithub CloudFormation.yaml --template-body file://CloudFormation.yaml
    finally:
      - echo This always runs even if the update or install command fails 
 
