Resources: 
  myfirstsecuritygroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable HTTP access via port 80 locked down to the load balancer + SSH access"
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: '80'
        IpProtocol: tcp
        ToPort: '80'
      - CidrIp: 0.0.0.0/0
        FromPort: '22'
        IpProtocol: tcp
        ToPort: '22'
  MyFirstEC2: 
    Type: AWS::EC2::Instance
    Properties: 
    ImageId: ami-095cd038eef3e5074
      KeyName: "EC2Key"
